export type Status = "todo" | "in progress" | "done" | "canceled" | "backlog"
export type Priority = "low" | "medium" | "high"

export type Task = {
  id: string
  title: string
  status: Status
  priority: Priority
  label: "documentation" | "bug" | "feature"
}

export const tasks: Task[] = [
  {
    id: "TASK-8782",
    title: "You can't compress the program without quantifying the open-source SSD!",
    status: "in progress",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-7878",
    title: "Try to calculate the EXE feed, maybe it will index the multi-byte pixel!",
    status: "backlog",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-7839",
    title: "We need to bypass the neural TCP card!",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-5562",
    title: "The SAS interface is down, bypass the open-source pixel so we can back ...",
    status: "backlog",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8686",
    title: "I'll parse the wireless SSL protocol, that should driver the API panel!",
    status: "canceled",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-9245",
    title: "Implement OAuth2 authentication flow for API endpoints",
    status: "in progress",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-8821",
    title: "Optimize database query performance for user dashboard",
    status: "todo",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-7734",
    title: "Fix memory leak in WebSocket connection handler",
    status: "in progress",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-6542",
    title: "Update API documentation for new endpoints",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-9132",
    title: "Implement rate limiting for public API endpoints",
    status: "todo",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8873",
    title: "Add unit tests for authentication middleware",
    status: "backlog",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7456",
    title: "Debug CSS rendering issues in Safari browser",
    status: "in progress",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-6998",
    title: "Implement dark mode theme switching",
    status: "done",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-9001",
    title: "Set up CI/CD pipeline for automated deployments",
    status: "in progress",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-8445",
    title: "Fix cross-browser compatibility issues",
    status: "todo",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-7223",
    title: "Implement real-time notification system",
    status: "backlog",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-6789",
    title: "Optimize image loading and caching",
    status: "done",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8234",
    title: "Add error boundary handling for React components",
    status: "todo",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7112",
    title: "Update security protocols for data encryption",
    status: "in progress",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-6432",
    title: "Fix mobile responsive layout issues",
    status: "done",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-9876",
    title: "Implement multi-language support",
    status: "backlog",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8654",
    title: "Optimize Redux store performance",
    status: "todo",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7543",
    title: "Fix user session handling bugs",
    status: "in progress",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-6321",
    title: "Update API versioning documentation",
    status: "done",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-9564",
    title: "Implement file upload progress tracking",
    status: "todo",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8123",
    title: "Add end-to-end testing suite",
    status: "backlog",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7890",
    title: "Fix data synchronization issues",
    status: "in progress",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-6789",
    title: "Create user onboarding documentation",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-9432",
    title: "Implement password reset functionality",
    status: "todo",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-8765",
    title: "Optimize database indexing",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7654",
    title: "Fix form validation errors",
    status: "done",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-6543",
    title: "Update API integration guide",
    status: "backlog",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-9234",
    title: "Implement user activity logging",
    status: "todo",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8432",
    title: "Add automated backup system",
    status: "in progress",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-7321",
    title: "Fix memory leaks in image processing",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-6234",
    title: "Create API migration guide",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-9123",
    title: "Implement social media authentication",
    status: "backlog",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8321",
    title: "Optimize frontend bundle size",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7234",
    title: "Fix cache invalidation issues",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-6123",
    title: "Update security best practices guide",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-9345",
    title: "Implement push notifications",
    status: "backlog",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8234",
    title: "Add GraphQL query optimization",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7123",
    title: "Fix data race conditions",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-6432",
    title: "Create deployment documentation",
    status: "done",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-9567",
    title: "Implement multi-factor authentication",
    status: "backlog",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-8765",
    title: "Add performance monitoring tools",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7654",
    title: "Fix API rate limiting bugs",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-6789",
    title: "Update troubleshooting guide",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-9876",
    title: "Implement data export functionality",
    status: "backlog",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8987",
    title: "Add automated code quality checks",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7890",
    title: "Fix authentication token expiry issues",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-6543",
    title: "Create API changelog documentation",
    status: "done",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-9654",
    title: "Implement user role management",
    status: "backlog",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-8765",
    title: "Add database migration scripts",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7876",
    title: "Fix websocket connection issues",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-6987",
    title: "Update API reference documentation",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-9789",
    title: "Implement email notification system",
    status: "backlog",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8890",
    title: "Add service worker for offline support",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7789",
    title: "Fix database deadlock issues",
    status: "todo",
    label: "bug",
    priority: "high",
  }
]

